services:
  deepseek-ocr-webui:
    build: .
    container_name: deepseek-ocr-webui
    ports:
      - "8001:8001"
    volumes:
      - ./models:/app/models  # Mount directory for model weights
      - ./webui_uploads:/app/webui_uploads  # Upload directory
      - ./webui_results:/app/webui_results  # Results directory
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - MODEL_PATH=/app/models/deepseek-ai/DeepSeek-OCR  # Update with your model path
      - MAX_CONCURRENCY=5  # Adjust based on your GPU memory
      - GPU_MEMORY_UTILIZATION=0.85  # Adjust based on your GPU memory
      - SERVER_MODE=webui  # Use Web UI mode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # Give time for model to load
